function [ handles ] = setDefaultValues( handles )
global settings;
global g_positions;
global connections;
global settings_rf;
global draw;
global calibrations;
global pmeters;
global dpi_values;
global fmulti;
global ag_oscilloscope;
connections.sa_connected=0;
connections.rfdc_connected=0;
connections.pm_forward=0;
connections.pm_reflected=0;
connections.fluke_connected=0;
connections.osc_connected=0;
set(handles.visa_address,'String','USB0::0x0957::0x173D::MY50340261::0::INSTR');
ag_oscilloscope.visa_address = 'USB0::0x0957::0x173D::MY50340261::0::INSTR';
set(handles.gpib_fluke,'String','23');
fmulti.gpib_fluke='23';
set(handles.fluke_voltage,'String','?');
fmulti.fluke_voltage='?';
set(handles.set_fspace,'Value',2);
dpi_values.fspace=2;
set(handles.set_fmin,'String','10');
dpi_values.fmin='10';
set(handles.set_fmax,'String','1000');
dpi_values.fmax='1000';
set(handles.set_fstep,'String','20');
dpi_values.nstep='20';
set(handles.dpi_funit,'Value',3);
dpi_values.dpi_funit=3;
set(handles.set_pmin,'String','-30');
dpi_values.pmin='-30';
set(handles.set_pmax,'String','0');
dpi_values.pmax='0';
set(handles.set_pstep,'String','3');
dpi_values.pstep='3';
set(handles.dpi_low,'String','4.9');
dpi_values.dpi_low='4.9';
set(handles.dpi_high,'String','5.1');
dpi_values.dpi_high='5.1';
set(handles.get_forward_power,'String','?');
pmeters.forward_power='?';
set(handles.get_reflected_power,'String','?');
pmeters.reflected_power='?';
set(handles.com_forward,'String','COM4');
pmeters.com_forward='COM4';
set(handles.com_reflected,'String','COM3');
pmeters.com_reflected='COM3';
set(handles.baud_forward,'String','115200');
pmeters.baud_forward='115200';
set(handles.baud_reflected,'String','115200');
pmeters.baud_reflected='115200';
set(handles.filter_forward,'Value',8);
pmeters.filter_forward=8;
set(handles.filter_reflected,'Value',8);
pmeters.filter_reflected=8;
set(handles.x_position,'String','5');
g_positions.x_position='5';
set(handles.y_position,'String','5');
g_positions.y_position='5';
set(handles.x_step,'String','1');
g_positions.x_step='1';
set(handles.y_step,'String','1');
g_positions.y_step='1';
set(handles.level_rfdc,'String','15');
settings_rf.rfdc.level_value='15';
set(handles.level_unit_rfdc,'Value',1);
settings_rf.rfdc.level_unit=1;
set(handles.freq_rfdc,'String','5');
settings_rf.rfdc.freq_value='5';
set(handles.frequency_unit_rfdc,'Value',3);
settings_rf.rfdc.freq_unit=3;
draw.frequency_search=5;
set(handles.set_frequency,'String','5');
draw.frequency_search_unit=3;
set(handles.popup_set_frequency,'Value',3);
draw.x_coor='0';
draw.y_coor='0';
set(handles.graph_pop,'Value',2);
draw.graph_print=2;
set(handles.ref_point_coor,'String','0,0');
calibrations.x=0;
calibrations.y=0;
calibrations.z=0;
set(handles.center_span_frequency,'Value',1);
set(handles.start_stop_frequency,'Value',0);
settings.sa.cs_button=1;
set(handles.center_freq_num, 'String', '5');
settings.sa.freq_center='5';
set(handles.span_freq_num,'String','2');
settings.sa.freq_span='2';
set(handles.center_freq_unit,'Value',3);
settings.sa.freq_cs_unit=3;
set(handles.ref_level,'String','15');
settings.sa.ref_level='15';
set(handles.ref_level_unit,'Value',1);
settings.sa.ref_level_unit=1;
set(handles.sweep_time,'String','300');
settings.sa.sweep_time_num='300';
set(handles.sweep_points,'Value',2);
settings.sa.sweep_points=2;
set(handles.sweep_unit,'Value',1);
settings.sa.sweep_time_unit=1;
set(handles.rbw_unit,'Value',9);
settings.sa.rbw=9;
set(handles.vbw_unit,'Value',12);
settings.sa.vbw=12;
set(handles.unit_y_scale,'Value',1);
settings.sa.y_scale=1;
set(handles.peak_button,'Value',1);
settings.sa.peak=1;
settings.rfdc_gpib=28;
settings.sa_gpib=18;
end

